[project]
name = "example-server"
version = "0.1.0"
description = "Template project for LangGraph-based agent server."
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.2",
]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"
